### ISSUE TITLE
 文章中插入音乐

### ISSUE THREAD

**Issue by helei112g** [zchen9/hexo-theme-hollow#1]
hi，你好！
   这个主题非常漂亮。昨天刚接触hexo。想用你的这个主题在github上搭一个博客。请问，你文章中，如何插入音乐的呢？

**Comment by ch1oechao** [comment]
音乐部分是插入了网易云音乐的插件
随机选一首歌  http://music.163.com/#/song?id=30474547 
然后就有一个生成外链播放器的链接 点击进去就可以看到插件配置了

**Comment by helei112g** [comment]
非常感谢。另外你的博客，

**Comment by helei112g** [comment]
另外，你的博客( http://www.chen9.info/) 首页上的页面是如何生成的？还有这个：(http://www.chen9.info/code/)  页面。我需要做什么配置呢？  问题有点多。这个是我当前生成出来的 博客 (https://helei112g.github.io/)

**Comment by ch1oechao** [comment]
文章要生成预览的话需要添加 ，即：

```
预览...

<!--more-->

正文...
```

另外 
主页repo 在 https://github.com/zchen9/zchen9.github.io
code部分在 https://github.com/zchen9/code
我把它们都抽离出来了 用 gh-pages 的形式生成网页 用链接的形式连起来

**Comment by helei112g** [comment]
那这样子，我怎么直接通过  hexo generate  生成呢？是不是说相当于是两个主题？我要分开操作吗？

**Comment by ch1oechao** [comment]
主页和 code 部分用的 jekyll... 比 hexo 操作方便一丢丢 -。

**Comment by helei112g** [comment]
嗯。非常感谢。一个做后端的工程师对前端不甚了解。谢谢   你说的jekyll是另一个博客系统吗？那么你对应使用的主题 是否方便提供下？

**Comment by ch1oechao** [comment]
jekyll的主题文件是和文章在一起的
