### ISSUE TITLE
宋体字在win环境下显示体验很差

### ISSUE THREAD

**Issue by Wyatt-404** [zchen9/hexo-theme-hollow#13]
在mac下，宋体的渲染效果很不错，如图：

![macos](http://ooovwni5a.bkt.clouddn.com/20170525121426_ko8Acm_QQ20170525-120748.jpeg)

但是在win下面的体验就很差了。
![win](http://ooovwni5a.bkt.clouddn.com/20170525121409_Ps2ZuJ_QQ20170525-120830.jpeg)

建议可以使用思源宋体，效果很赞。
https://sspai.com/post/38705

**Comment by ch1oechao** [comment]
感谢推荐字体，这周更新~

**Comment by ch1oechao** [comment]
字体已更新~
