### ISSUE TITLE
首页大标题

### ISSUE THREAD

**Issue by Funhity** [zchen9/hexo-theme-hollow#14]
你好，请教一下这个首页怎么显示一个小标题和内容，我安装之后只显示标题了，麻烦问下分类啥的怎么配置

**Comment by luke11986** [comment]
我猜是你的post中title的md格式不对，所以显示了默认的标题吧

**Comment by luke11986** [comment]
npm install hexo-excerpt --save

**Comment by ch1oechao** [comment]
Duplicate of #5
