### ISSUE TITLE
左标题右简介的设计在移动端上水土不服

### ISSUE THREAD

**Issue by ghost** [zchen9/hexo-theme-hollow#2]
作者你好，感谢你设计并实现了如此简约又文艺的主题。

只不过在移动端，字体似乎没能按照预计的设计显示，而且左侧的标题在移动端也在左侧，显得十分拥挤。

可否考虑下移动端适配？

**Comment by ch1oechao** [comment]
嗯 看来移动端需求还是有的 哈哈 我会重新整顿一下移动端的 

另外 还有什么好的建议吗 😉

**Comment by ch1oechao** [comment]
我慎重考虑了一下移动端布局的问题 
感觉保持原样的左右布局还是可以接受的? 
如果搞成普通的上下的话就没有感觉了 😳

**Comment by ghost** [comment]
@zchen9 左右可以，但在移动端 Safari 上的字体希望能和桌面端一致。（还是 Safari 的锅呢？？）

觉得左右挤是因为自己在还在用4寸屏手机吧:trollface:

如果在右侧的简介显示引文的话会有显示Bug（桌面端Safari和Chrome均出现），建议重新设计下引文（quote）的样式以更加符合文艺气息。:new_moon_with_face:

<img width="880" alt="screen shot 2016-08-17 at 00 55 55" src="https://cloud.githubusercontent.com/assets/20040212/17708002/7c2b3cb0-6415-11e6-9bbf-b61d06e34c13.png">

**Comment by ch1oechao** [comment]
好的 我会尽快修复的

**Comment by ch1oechao** [comment]
预览部分的引用样式修复好啦 
风格主要以简约为主 所以在主页预览部分 不多加文字样式 保持原样~

**Comment by ghost** [comment]
移动端的字体希望能跟桌面端一致

![img_0183](https://cloud.githubusercontent.com/assets/20040212/18026251/0b8cd052-6c73-11e6-828d-aad71b7ae443.jpg)

**Comment by ch1oechao** [comment]
哈哈哈哈 感谢对主题的严格要求
我试了试在 `font-famliy` 加 `!important` 貌似也不行
我查了一下 手机端一般都会设置默认字体 你可以看看这篇文章 http://www.cnblogs.com/PeunZhang/p/3592096.html
移动端推荐使用的是 `font-family: Helvetica,sans-serif;` https://segmentfault.com/a/1190000003908191 第二十条

**Comment by ghost** [comment]
同为无衬线字体，的确没有必要以拖慢载入速度为代价替换字体。

但本主题在桌面端采用了某种衬线字体，在移动端用无衬线体感觉不是同一个主题；望请考虑。

（天猫商城在桌面web端也没使用衬线体）
