### ISSUE TITLE
How to prevent theme auto add <a> tag in article list?

### ISSUE THREAD

**Issue by xubihang** [zchen9/hexo-theme-hollow#26]
While using this theme, the generated home page/article list page always auto add an <a> tag to the description of each blog, turning which into a link(so as the style). 
I was using  tag to specify the description. Did I do something incorrectly? Or is there any methods to prevent automated add <a> tag?
使用主题生成页面后，在首页的文章列表中，文章的描述会被加上 a 标签，成为红色的链接样式。而我的文章中本身这部份不是链接。我这边是使用 more 标签之上的部分作为描述的。有什么方式可以避免出现这个问题么？非常感谢。

**Comment by ch1oechao** [comment]
检查下格式是否正确

```
title: 标题
category: 类别
date: 2020-02-20

---

预览

<!--more-->

正文
```

然后 `hexo clean`，`hexo g -d`

**Comment by xubihang** [comment]
似乎发现问题出现的情况了。当`<!--more-->`标签前后没有换行时，就会自动加上链接样式，如果有空行就可以了。
Adding a line before and after  `<!--more-->` tag works fine.

**Comment by ch1oechao** [comment]
好的，感谢反馈~
