### ISSUE TITLE
font依赖加载失败

### ISSUE THREAD

**Issue by hk93211** [zchen9/hexo-theme-hollow#27]
最近一段时间出现了http://cdn.bootcss.com/font-awesome/4.5.0/fonts/fontawesome-webfont.woff2?v=4.5.0这个font的依赖加载失败, 以前是没有问题的, 导致主题的字体感觉跟以前不一样了, 是否是我们的网络原因, 您那边加载的出来吗 ?

**Comment by ch1oechao** [comment]
可能是网络问题噢 0.0 被墙了？
