### ISSUE TITLE
新功能请查收哦~

### ISSUE THREAD

**Issue by fakeyanss** [zchen9/hexo-theme-hollow#35]
[Update]添加功能: 
1. 增加service worker 
2. 本地搜索 
3. 文章图片放大查看 

三个功能均在`_config.yml` 中可配置。

另外，整理了CSS样式（包含上次提交的）。

已提交 pull request #36

**Comment by ch1oechao** [comment]
你怎么这么厉害 🤣

**Comment by ch1oechao** [comment]
已合入，THX~

**Comment by LGDZEALER** [comment]
小白弱弱的问一句，怎么更新？

**Comment by LGDZEALER** [comment]
貌似本地搜索没有起作用？是我的打开方式不对嘛2333

**Comment by fakeyanss** [comment]
@LGDZEALER 你看看 package.json 里有没有 `hexo-generator-feed`，没有的话就 `npm install hexo-generator-feed --save`，对一下[我的仓库](https://github.com/fakeYanss/fakeyanss.github.io)里的配置，主要就两个_config.json 文件，没有太难找的地方。
![image](https://user-images.githubusercontent.com/30440198/57993480-b2f7d380-7aeb-11e9-8925-0578558db483.png)

**Comment by LGDZEALER** [comment]
`hexo-generator-feed `已经安装了，配置文件我对比后确实有不同地方，但是我也不敢乱动...

**Comment by fakeyanss** [comment]
@LGDZEALER 在站点的[_config.yml](https://github.com/fakeYanss/fakeyanss.github.io/blob/e2aa3ed3a64b59552a5c6556163449dfb28a8a6b/_config.yml#L60)配置feed的参数

在主题的[_config.yml](https://github.com/fakeYanss/fakeyanss.github.io/blob/e2aa3ed3a64b59552a5c6556163449dfb28a8a6b/themes/hollow/_config.yml#L19) 打开开关

**Comment by LGDZEALER** [comment]
主题`_config.yml`的开关已经打开，但是站点的`_config.yml`如何配置feed参数可以详细说一下嘛？
感谢🙏

**Comment by fakeyanss** [comment]
上面的链接里有，把那几行复制过去就行
________________________________

**Comment by LGDZEALER** [comment]
![](http://ww4.sinaimg.cn/large/006tNc79ly1g38nqtq97nj31e10u0wi9.jpg)
![](http://ww3.sinaimg.cn/large/006tNc79ly1g38nrnuduwj31a60u0dow.jpg)
![](http://ww3.sinaimg.cn/large/006tNc79ly1g38nrtenjxj31a60u0grg.jpg)
![](http://ww4.sinaimg.cn/large/006tNc79ly1g38ns1kftpj310n0u0q8d.jpg)

这样设置对吗？

**Comment by fakeyanss** [comment]
对，然后你本地执行

npm i
hexo clean
hexo g
hexo s

试试看??
________________________________

**Comment by LGDZEALER** [comment]
第一张图片就是hexo s 之后的，我搜索“周末”不应该搜到《周末记》这篇文章嘛？

**Comment by fakeyanss** [comment]
把你hexo g的日志贴一下
________________________________

**Comment by LGDZEALER** [comment]
![](http://ww1.sinaimg.cn/large/006tNc79ly1g38o5rmiknj30v80u0489.jpg)

**Comment by LGDZEALER** [comment]
[https://zealer.gitee.io/l1kemyself/](url)
这是我的博客网址

**Comment by fakeyanss** [comment]
atom文件是有的，检查一下文件内容，然后看下搜索的时候浏览器控制台有没有报错
________________________________

**Comment by LGDZEALER** [comment]
![](http://ww2.sinaimg.cn/large/006tNc79ly1g38odb9nhnj30vi06kgmw.jpg)
确实报错了！
我需要从哪里排查呢？

**Comment by LGDZEALER** [comment]
https://zealer.gitee.io/l1kemyself/

这是我的博客网址

**Comment by fakeyanss** [comment]
这是博客路径的问题，你贴一下站点config
________________________________

**Comment by LGDZEALER** [comment]
`# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: L1keMyself
subtitle:
description:
keywords:
author: L1keMyself
language:
timezone: 

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://zealer.gitee.io/l1kemyself/
root: /L1keMyself
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: hollow

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://gitee.com/ZEALER/L1keMyself.git
  branch: blog

  ### feed
feed:
  type: atom
  path: atom.xml
  limit: 0
  hub:
  order_by: -date
  icon: https://foreti.me/imgplace/2019/logo2.png
`

**Comment by LGDZEALER** [comment]
https://gitee.com/ZEALER/L1keMyself.git

**Comment by fakeyanss** [comment]
看起来是root写错了，后面加一个斜杠
________________________________

**Comment by LGDZEALER** [comment]
![](http://ww3.sinaimg.cn/large/006tNc79ly1g38p8qh7hpj317h0u0drc.jpg)

是在这里的后面加斜杠嘛？

**Comment by LGDZEALER** [comment]
![](http://ww3.sinaimg.cn/large/006tNc79ly1g38p8qh7hpj317h0u0drc.jpg)

是在这里的后面加斜杠嘛？

**Comment by fakeyanss** [comment]
上面的斜杠修改虽然和这次无关，但你的写法不对，最好也改一下
改成
```
url: https://www.chen9.info/fragment
root: /fragment/
```

---

我在search的文件中写死了查找路径，没考虑到博客不是用域名根目录的情况。
修改方法： 在你本地主题文件中找到search.ejs，在 hollow/layout/_partial/search.ejs
修改[这里](https://github.com/zchen9/hexo-theme-hollow/blob/7c8e756339cd206583155088fa242f4c577a3547/layout/_partial/search.ejs#L137)，
改成 
```
searchFunc("/l1kemyself//atom.xml", "local-search-input", "local-search-result");
```

**Comment by LGDZEALER** [comment]
![](http://ww2.sinaimg.cn/large/006tNc79ly1g38q90ped0j319b0u0n0q.jpg)

成功啦！非常感谢！

**Comment by LGDZEALER** [comment]
另外我有一个问题，虽然和这个问题无关但是我想问一下...
![](http://ww4.sinaimg.cn/large/006tNc79ly1g38qbbmfnnj30go03mglo.jpg)
![](http://ww3.sinaimg.cn/large/006tNc79ly1g38qbhlvi0j303i02iglg.jpg)

关于网页的图标和返回主页的图标应该在哪里添加或者修改呢？

**Comment by fakeyanss** [comment]
标签的图标：在根目录放一个文件，文件名favicon.ico

返回主页的图标：你得去hollow的layout文件夹里面去看在哪里做的，有兴趣的话就了解一下hexo在创建博客的时候做了哪些事情，读一下hollow这个主题下每个文件，由于设计简介，hollow应该是比较容易读懂的。

**Comment by LGDZEALER** [comment]
好的，非常感谢！
