### ISSUE TITLE
日期问题

### ISSUE THREAD

**Issue by xjtu-blacksmith** [zchen9/hexo-theme-hollow#38]
在主题的 `_config.yml` 文件中，定义了中文格式的 `data_format` 属性。现在我想使用英文作为站点的语言，这一项信息能否像 `languages` 文件夹下的参数一样随语言变动？

把仓库 clone 过来是可以自己改的，不过我想用 submodule 功能与本仓库同步 :cry:

**Comment by ch1oechao** [comment]
我 get 到你的意思了，是希望 `date_format` 由博客主体 `_config.yml` 控制，不是主题控制对吧？

**Comment by xjtu-blacksmith** [comment]
简单说就是语言变成英文之后，日期格式没变……不知道有无可能与语言一起改

能由博客主体来改也可，当时没有找到修改的入口

**Comment by ch1oechao** [comment]
已修复，优先取博客时间设置~
