### ISSUE TITLE
给主题增加了主页背景和随机名言

### ISSUE THREAD

**Issue by F7ionsy** [zchen9/hexo-theme-hollow#40]
http://f7ionsy.me/

**Comment by ch1oechao** [comment]
主页视频很赞 👍，有没有兴趣抽成一个封面功能？

**Comment by F7ionsy** [comment]
> 主页视频很赞 👍，有没有兴趣抽成一个封面功能？

像是你的home页是吗？

**Comment by ch1oechao** [comment]
对的~

**Comment by F7ionsy** [comment]
> 对的〜

https://lihengdong.com/indexpage/
请查收

**Comment by ch1oechao** [comment]
可以给代码链接看看吗~

**Comment by F7ionsy** [comment]
> 可以给代码链接看看吗~

https://github.com/F7ionsy/indexpage
