### ISSUE TITLE
关于首页

### ISSUE THREAD

**Issue by Asthestarsfalll** [zchen9/hexo-theme-hollow#47]
你好，很喜欢你的主题！
但是我的首页没有下一页，而是这样一长串的
![image](https://user-images.githubusercontent.com/72954905/130401394-fa2f3cc5-fe19-4d64-adc7-32efe122bb60.png)

**Comment by AtomAlpaca** [comment]
请检查博客全局配置文件，即博客根目录下的配置文件 `_config.yml` 中 `index_generator` 下 `per_page` 的值是否为零
该选项为零时博客将禁用首页的分页功能

**Comment by Asthestarsfalll** [comment]
已解决
