### ISSUE TITLE
图片居中

### ISSUE THREAD

**Issue by Asthestarsfalll** [zchen9/hexo-theme-hollow#48]
请问怎么设置图片居中呢，我改了styl文件，但是并没有生效

**Comment by AtomAlpaca** [comment]
可以试试在markdown文件内部嵌入HTML代码
``` html
<div align="center">
    <img src="..." width="100" height="100" >
</div>
```

**Comment by Asthestarsfalll** [comment]
@AtomAlpaca 感谢，可以了，不过每次这样的话有点麻烦，请问代码中直接改吗？

**Comment by AtomAlpaca** [comment]
我不太会改欸...

**Comment by AtomAlpaca** [comment]
@Asthestarsfalll 
测试了一下, 将 `/themes/hollow/source/css/article.styl` 中第 16 行的 `display inline-block` 改成 `display block` 就可以使图片默认居中

**Comment by Asthestarsfalll** [comment]
@AtomAlpaca 十分感谢！！！
