### ISSUE TITLE
关于pre

### ISSUE THREAD

**Issue by Asthestarsfalll** [zchen9/hexo-theme-hollow#50]
你好！再次打扰了！
请问pre这部分在哪里修改
![image](https://user-images.githubusercontent.com/72954905/134276981-c697bfa3-d9c6-47d1-b1f4-67215c056d57.png)
![image](https://user-images.githubusercontent.com/72954905/134276997-1c51645e-5d22-4088-b4b5-a482bb4bad62.png)
原来的太小了，想放大点，但是没有找到在哪里修改
感谢！

**Comment by Asthestarsfalll** [comment]
另外想问一下目录能够在front matter中设置是否启用吗

**Comment by Asthestarsfalll** [comment]
> 另外想问一下目录能够在front matter中设置是否启用
将toc.ejs中的theme.toc.enable改为page.toc即可，front matter对应设置toc: true或者false

**Comment by AtomAlpaca** [comment]
在`themes/hollow/source/css/article.styl`文件末尾`pre`下添加`font-size 16px`就可以调整代码字体大小
```styl
pre
  font-size 16px //就像这样
  // Theme: Solarized - Light
  // More theme here: http://softwaremaniacs.org/media/soft/highlight/test.html
  .comment
  .template_comment
  .diff .header
  .doctype
  .pi
  .lisp .string
  .javadoc
    color #93a1a1
    font-style italic

```

**Comment by AtomAlpaca** [comment]
@Asthestarsfalll

**Comment by Asthestarsfalll** [comment]
@AtomAlpaca 感谢，已解决！
