### ISSUE TITLE
你好，我的搜索功能为什么没法用，也米有小相机

### ISSUE THREAD

**Issue by He1o** [zchen9/hexo-theme-hollow#51]
你好，我的搜索功能为什么没法用，也米有小相机

**Comment by AtomAlpaca** [comment]
## 搜索功能
搜索功能是依赖于插件 `hexo-generator-feed` 的，hexo 默认不提供这个插件，需要手动安装才能生效。
安装方式: 在博客根目录打开终端，运行
``` bash
npm install hexo-generator-feed --save
```
如果你和我一样是中国大陆用户，可以在末尾添加
``` bash
--registry https://registry.npm.taobao.org
```
加快安装速度

## 小相机
小相机功能作者没有给出使用指南，但注意到 `hollow/layout/_partial/gosite.ejs` 中
``` ejs
<% if (config.baseurl) { %>
<a class="nav-back" href="<%- config.baseurl %>">
    <i class="fa fa-camera-retro"></i>
</a>
<% } %>
```
我们可以在博客根目录的 `_config.yml` 文件末尾添加
``` yml
baseurl: 'yourURL'
```
如想要跳转到 [https://example.com](https://example.com)，则添加
``` yml
baseurl: 'https://example.com'
```

或者，你也可以直接修改 `gosite.ejs`，如修改为

``` ejs
<a class="nav-back" href="https://example.com">
    <i class="fa fa-camera-retro"></i>
</a>
```
@He1o

**Comment by He1o** [comment]
3q，太感谢了，你好棒！
@AtomAlpaca
