### ISSUE TITLE
markdown的有序列表不识别

### ISSUE THREAD

**Issue by He1o** [zchen9/hexo-theme-hollow#54]
![image](https://user-images.githubusercontent.com/57656907/142368324-be20fd8a-4ece-4a09-802b-d48f5dffac4f.png)

**Comment by He1o** [comment]
好像这是我自己的问题，有谁能救救孩子吗？

**Comment by AtomAlpaca** [comment]
不是很知道楼主的`markdown`里具体是什么情况，但是在我的test页面上是正常的，这里摘录页面地址、预览效果、部分渲染生成代码以及`markdown`部分源码，希望对楼主有帮助

[传送门!](https://blog.atal.moe/2021/Test/)

![Screenshot 2021-11-19 at 19-52-49 Test AtomAlpaca's Blog](https://user-images.githubusercontent.com/66774326/142618891-775d90f1-36cd-4b9b-a850-b058b95e8cc1.png)
``` html
<ol>
<li>Test</li>
<li>Test</li>
<li>Test</li>
<li>Also Test</li>
</ol>
```
``` markdown
1. Test
2. Test
3. Test
4. Also Test
```

**Comment by Chlience** [comment]
请问您是如何加入 mathjax 支持的，求助

**Comment by He1o** [comment]
> 请问您是如何加入 mathjax 支持的，求助

https://www.cnblogs.com/zhyantao/p/10424874.html
https://blog.csdn.net/weixin_44441126/article/details/119745642

可以查看这两篇博客
注意星号要用 \ast 不要直接打 * ，否则多个 *会解析成强调
@Chlience

**Comment by Chlience** [comment]
> > 请问您是如何加入 mathjax 支持的，求助
> 
> https://www.cnblogs.com/zhyantao/p/10424874.html https://blog.csdn.net/weixin_44441126/article/details/119745642
> 
> 可以查看这两篇博客 注意星号要用 \ast 不要直接打 * ，否则多个 *会解析成强调 @Chlience

非常感谢 已经成功添加支持了
