### ISSUE TITLE
请问翻页怎么配置

### ISSUE THREAD

**Issue by no-today** [zchen9/hexo-theme-hollow#60]
我看作者博客有，但是我自个找不到配置的地方

**Comment by AtomAlpaca** [comment]
需要配置博客全局配置文件，即博客根目录下的配置文件 `_config.yml` 中 `index_generator` 下 `per_page` 选项，这个选项的值是一个整数，代表每页的博文数量。特别地，这个值为 0 时会禁用翻页。

**Comment by no-today** [comment]
> 需要配置博客全局配置文件，即博客根目录下的配置文件 `_config.yml` 中 `index_generator` 下 `per_page` 选项，这个选项的值是一个整数，代表每页的博文数量。特别地，这个值为 0 时会禁用翻页。
谢谢你
