### ISSUE TITLE
文章摘要中部分段落文字会出现红色字体带下划线的链接

### ISSUE THREAD

**Issue by ammeto** [zchen9/hexo-theme-hollow#9]
![sp161110_161729](https://cloud.githubusercontent.com/assets/21106176/20169223/3c5243ce-a761-11e6-99b6-f7b0735413bf.png)
网站首页文章摘要部分出现了红色字体带下划线的链接，我是hexo直接换主题后就出现了这样的问题，还有，希望博主把那个带照片的页面也加进去，觉得挺好看的。

**Comment by ch1oechao** [comment]
链接部分是生成的时候编译成链接了吗？你有没有 hexo clean 一下？
带照片的页面是哪个？

**Comment by ammeto** [comment]
没有加链接的，我在之前的yelee主题下编译是没有问题的，只是按你github上的要求改换了主题，显示后的效果就是上面那样，你也可以看看https://ammeto.github.io/，hexo clean了
![sp161111_171507](https://cloud.githubusercontent.com/assets/21106176/20210022/6da49ec8-a832-11e6-87c1-5acaaf36a74f.png)

**Comment by ammeto** [comment]
没有加链接的，我在之前的yelee主题下编译是没有问题的，只是按你github上的要求改换了主题，显示后的效果就是上面那样，你也可以看看https://ammeto.github.io/  
已经hexo clean了
![sp161111_171507](https://cloud.githubusercontent.com/assets/21106176/20210094/b9530d0a-a832-11e6-9675-9b6c7843a19a.png)

**Comment by baxsad** [comment]
我也是同样问题

**Comment by ammeto** [comment]
博主，这个问题是特殊情况吗？我说的那个带照片的页面是你网站首页，不是fragment那一页。还想问一下博主，图床链接插入图片，插入网易云音乐的音乐，都不会正常显示，或者说不会显示，到底是什么问题，之前用的各主题也会这样，会不会是github默认的https影响的？

**Comment by ch1oechao** [comment]
@ammeto 
animation应该是没有import 我会尽快修复的
图片用的七牛 只支持http吧 https需要申请新的链接
网易云音乐 我之前试过 貌似不支持https...

**Comment by racall** [comment]
主题很漂亮
